apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin-cd-binding
subjects:
  # Подключаем к кластерному роли Service Account из namespace homework
  - kind: ServiceAccount
    name: cd-admin
    namespace: homework
roleRef:
  # Ссылаемся на метаданные созданного нами ClusterRole
  kind: Role
  name: cd-admin
  apiGroup: rbac.authorization.k8s.io