apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-pvc
  namespace: homework
spec:
  accessModes:
    - - {{ include "homework.pv.accessModes"} }
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.volumes.pvc.capacity }}