apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  namespace: homework
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
    - protocol: TCP
      port: {{ .Values.ports.containerPortPod }}
      targetPort: {{ .Values.ports.containerPort }}
  type: ClusterIP
