apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homework-pvc
  namespace: homework
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  # storageClassName: slow
  # selector:
  #   matchLabels:
  #     release: "stable"
    # matchExpressions:
    #   - {key: environment, operator: In, values: [dev]}